### ISSUE TITLE
i2c master - Does not return result

### ISSUE THREAD

**Issue by Lenart12** [DavidAntliff/esp32-poolmon#2]
I assume you meant to return the result.
https://github.com/DavidAntliff/esp32-poolmon/blob/8aa4344a04acc18437d25598eaca535812642b16/main/i2c_master.c#L107

**Comment by DavidAntliff** [comment]
@Lenart12 I'm not sure I fully understand - there's a return statement on line 112 (admittedly the formatting seems to have been messed up, so it's not obvious):

https://github.com/DavidAntliff/esp32-poolmon/blob/8aa4344a04acc18437d25598eaca535812642b16/main/i2c_master.c#L112

Thanks for taking a look at the code though - are you interested in using some of it? Happy to answer any questions you might have.

**Comment by Lenart12** [comment]
Oh I didn't see that excuse me :o . Yeah I was looking to see how you made I2C threadsafe thanks for the quick reply
